INSERT INTO REPO_INFO (FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)
VALUES ('kvbqq/test-repo', 'desc', 'url', 1, '2025-05-25');
INSERT INTO REPO_INFO (FULL_NAME, DESCRIPTION, CLONE_URL, STARS, CREATED_AT)
VALUES ('kvbqq/delete-repo', 'delete', 'url2', 0, '2025-02-13');